name: 'PR Post Merge Actions'
description: 'PR Post Merge Actions'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  REPOSITORY:
    description: 'Repository'
    required: true
  PR:
    description: 'Pull Request Number'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'